export const CHILD_RANDOM_SEARCH_REQUEST = 'CHILD_RANDOM_SEARCH_REQUEST';
export const CHILD_RANDOM_SEARCH_SUCCESS = 'CHILD_RANDOM_SEARCH_SUCCESS';
export const CHILD_RANDOM_SEARCH_FAIL = 'CHILD_RANDOM_SEARCH_FAIL';
export const CHILD_RANDOM_SEARCH_RESET = 'CHILD_RANDOM_SEARCH_RESET';

export const CHILD_SEARCH_RESULT_REQUEST = 'CHILD_SEARCH_RESULT_REQUEST';
export const CHILD_SEARCH_RESULT_SUCCESS = 'CHILD_SEARCH_RESULT_SUCCESS';
export const CHILD_SEARCH_RESULT_FAIL = 'CHILD_SEARCH_RESULT_FAIL';
export const CHILD_SEARCH_RESULT_RESET = 'CHILD_SEARCH_RESULT_RESET';

export const CHILD_BY_ID_REQUEST = 'CHILD_BY_ID_REQUEST';
export const CHILD_BY_ID_SUCCESS = 'CHILD_BY_ID_SUCCESS';
export const CHILD_BY_ID_FAIL = 'CHILD_BY_ID_FAIL';
