export const CHILD_RANDOM_SEARCH_REQUEST = 'CHILD_RANDOM_SEARCH_REQUEST';
export const CHILD_RANDOM_SEARCH_SUCCESS = 'CHILD_RANDOM_SEARCH_SUCCESS';
export const CHILD_RANDOM_SEARCH_FAIL = 'CHILD_RANDOM_SEARCH_FAIL';

export const CHILD_SEARCH_RESULT_REQUEST = 'CHILD_SEARCH_RESULT_REQUEST';
export const CHILD_SEARCH_RESULT_SUCCESS = 'CHILD_SEARCH_RESULT_SUCCESS';
export const CHILD_SEARCH_RESULT_FAIL = 'CHILD_SEARCH_RESULT_FAIL';
