export const FAMILY_NETWORK_REQUEST = 'FAMILY_NETWORK_REQUEST';
export const FAMILY_NETWORK_SUCCESS = 'FAMILY_NETWORK_SUCCESS';
export const FAMILY_NETWORK_FAIL = 'FAMILY_NETWORK_FAIL';

export const SIGNATURE_REQUEST = 'SIGNATURE_REQUEST';
export const SIGNATURE_SUCCESS = 'SIGNATURE_SUCCESS';
export const SIGNATURE_FAIL = 'SIGNATURE_FAIL';
