export const VIRTUAL_FAMILY_TOKEN_REQUEST = 'VIRTUAL_FAMILY_TOKEN_REQUEST';
export const VIRTUAL_FAMILY_TOKEN_SUCCESS = 'VIRTUAL_FAMILY_TOKEN_SUCCESS';
export const VIRTUAL_FAMILY_TOKEN_FAIL = 'VIRTUAL_FAMILY_TOKEN_FAIL';
