export const INVITE_TO_MY_FAMILY_REQUEST = 'INVITE_TO_MY_FAMILY_REQUEST';
export const INVITE_TO_MY_FAMILY_SUCCESS = 'INVITE_TO_MY_FAMILY_SUCCESS';
export const INVITE_TO_MY_FAMILY_FAIL = 'INVITE_TO_MY_FAMILY_FAIL';

export const JOIN_VIRTUAL_FAMILY_REQUEST = 'JOIN_VIRTUAL_FAMILY_REQUEST';
export const JOIN_VIRTUAL_FAMILY_SUCCESS = 'JOIN_VIRTUAL_FAMILY_SUCCESS';
export const JOIN_VIRTUAL_FAMILY_FAIL = 'JOIN_VIRTUAL_FAMILY_FAIL';
