export const SHAPARAK_PAYMENT_REQUEST = 'SHAPARAK_PAYMENT_REQUEST';
export const SHAPARAK_PAYMENT_SUCCESS = 'SHAPARAK_PAYMENT_SUCCESS';
export const SHAPARAK_PAYMENT_FAIL = 'SHAPARAK_PAYMENT_FAIL';
export const SHAPARAK_PAYMENT_RESET = 'SHAPARAK_PAYMENT_RESET';

export const CART_PAYMENT_REQUEST = 'CART_PAYMENT_REQUEST';
export const CART_PAYMENT_SUCCESS = 'CART_PAYMENT_SUCCESS';
export const CART_PAYMENT_FAIL = 'CART_PAYMENT_FAIL';
export const CART_PAYMENT_RESET = 'CART_PAYMENT_RESET';
