export const CHANGE_VERIFY_STEP = "CHANGE_VERIFY_STEP";

export const USER_VERIFY_CODE_REQUEST = "USER_VERIFY_CODE_REQUEST";
export const USER_VERIFY_CODE_SUCCESS = "USER_VERIFY_CODE_SUCCESS";
export const USER_VERIFY_CODE_FAIL = "USER_VERIFY_CODE_FAIL";
