export const CART_ADD_REQUEST = 'CART_ADD_REQUEST';
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS';
export const CART_ADD_FAIL = 'CART_ADD_FAIL';

export const CART_ADD_RESET = 'CART_ADD_RESET';

export const CART_BADGE_REQUEST = ' CART_BADGE_REQUEST';
export const CART_BADGE_SUCCESS = ' CART_BADGE_SUCCESS';
export const CART_BADGE_FAIL = ' CART_BADGE_FAIL';
export const CART_BADGE_RESET = ' CART_BADGE_RESET';
