export const CheckPointType = {
  FEATURE: 'feature',
  BUG_FIX: 'bug-fix',
  HOTFIX: 'hotfix',
  DEPLOY: 'deploy',
  ROLLBACK: 'rollback',
  DB_MIGRATION: 'db-migration',
  CODE_REVIEW: 'code-review',
  PERFORMANCE: 'performance',

  ROADMAP: 'roadmap',
  PRODUCT_SPEC: 'product-spec',
  USER_RESEARCH: 'user-research',
  TESTING: 'testing',

  DESIGN: 'design',
  UX: 'ux',
  BRANDING: 'branding',
  ASSET_PRODUCTION: 'asset-production',

  CONTENT: 'content',
  COPYWRITING: 'copywriting',
  SEO: 'seo',
  SOCIAL: 'social',
  EMAIL: 'email',
  PAID_ADS: 'paid-ads',
  CAMPAIGN: 'campaign',
  EXPERIMENT: 'experiment',

  SUPPORT: 'support',
  ONBOARDING: 'onboarding',
  SALES: 'sales',
  PARTNERSHIPS: 'partnerships',
  INCIDENT: 'incident',

  MONITORING: 'monitoring',
  BACKUP: 'backup',
  SECURITY: 'security',
  CONFIG: 'config',
  AUTOMATION: 'automation',
  LEGAL: 'legal',
  FINANCE: 'finance',
  HR: 'hr',
  MEETING: 'meeting',
  TRAINING: 'training',

  // New
  CHILD_JOINED: 'child-joined',
  SEASONAL_REPORT: 'seasonal-report',
};

export const CheckPointTypeLabel = {
  [CheckPointType.FEATURE]: 'Feature',
  [CheckPointType.BUG_FIX]: 'Bug',
  [CheckPointType.HOTFIX]: 'Hotfix',
  [CheckPointType.DEPLOY]: 'Deploy',
  [CheckPointType.ROLLBACK]: 'Rollback',
  [CheckPointType.DB_MIGRATION]: 'Migration',
  [CheckPointType.CODE_REVIEW]: 'Review',
  [CheckPointType.PERFORMANCE]: 'Perf',

  [CheckPointType.ROADMAP]: 'Roadmap',
  [CheckPointType.PRODUCT_SPEC]: 'Spec',
  [CheckPointType.USER_RESEARCH]: 'Research',
  [CheckPointType.TESTING]: 'Testing',

  [CheckPointType.DESIGN]: 'Design',
  [CheckPointType.UX]: 'UX',
  [CheckPointType.BRANDING]: 'Brand',
  [CheckPointType.ASSET_PRODUCTION]: 'Assets',

  [CheckPointType.CONTENT]: 'Content',
  [CheckPointType.COPYWRITING]: 'Copy',
  [CheckPointType.SEO]: 'SEO',
  [CheckPointType.SOCIAL]: 'Social',
  [CheckPointType.EMAIL]: 'Email',
  [CheckPointType.PAID_ADS]: 'Ads',
  [CheckPointType.CAMPAIGN]: 'Campaign',
  [CheckPointType.EXPERIMENT]: 'Experiment',

  [CheckPointType.SUPPORT]: 'Support',
  [CheckPointType.ONBOARDING]: 'Onboarding',
  [CheckPointType.SALES]: 'Sales',
  [CheckPointType.PARTNERSHIPS]: 'Partners',
  [CheckPointType.INCIDENT]: 'Incident',

  [CheckPointType.MONITORING]: 'Monitor',
  [CheckPointType.BACKUP]: 'Backup',
  [CheckPointType.SECURITY]: 'Security',
  [CheckPointType.CONFIG]: 'Config',
  [CheckPointType.AUTOMATION]: 'Automation',
  [CheckPointType.LEGAL]: 'Legal',
  [CheckPointType.FINANCE]: 'Finance',
  [CheckPointType.HR]: 'HR',
  [CheckPointType.MEETING]: 'Meeting',
  [CheckPointType.TRAINING]: 'Training',

  [CheckPointType.CHILD_JOINED]: 'Joined',
  [CheckPointType.SEASONAL_REPORT]: 'Report',
};
