export const WALLET_NONCE_REQUEST = 'WALLET_NONCE_REQUEST';
export const WALLET_NONCE_SUCCESS = ' WALLET_NONCE_SUCCESS';
export const WALLET_NONCE_FAIL = ' WALLET_NONCE_FAIL';

export const WALLET_VERIFY_REQUEST = 'WALLET_VERIFY_REQUEST';
export const WALLET_VERIFY_SUCCESS = ' WALLET_VERIFY_SUCCESS';
export const WALLET_VERIFY_FAIL = ' WALLET_VERIFY_FAIL';
export const WALLET_VERIFY_RESET = 'WALLET_VERIFY_RESET';

export const WALLET_INFORMATION_REQUEST = 'WALLET_INFORMATION_REQUEST';
export const WALLET_INFORMATION_SUCCESS = ' WALLET_INFORMATION_SUCCESS';
export const WALLET_INFORMATION_FAIL = ' WALLET_INFORMATION_FAIL';
export const WALLET_INFORMATION_RESET = ' WALLET_INFORMATION_RESET';

export const READY_TO_SIGN_ONE_NEED_REQUEST = 'READY_TO_SIGN_ONE_NEED_REQUEST';
export const READY_TO_SIGN_ONE_NEED_SUCCESS = 'READY_TO_SIGN_ONE_NEED_SUCCESS';
export const READY_TO_SIGN_ONE_NEED_FAIL = 'READY_TO_SIGN_ONE_NEED_FAIL';
export const READY_TO_SIGN_ONE_NEED_RESET = 'READY_TO_SIGN_ONE_NEED_RESET';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';
export const CREATE_COMMENT_RESET = 'CREATE_COMMENT_RESET';

export const ONE_NEED_COEFFS_REQUEST = 'ONE_NEED_COEFFS_REQUEST';
export const ONE_NEED_COEFFS_SUCCESS = 'ONE_NEED_COEFFS_SUCCESS';
export const ONE_NEED_COEFFS_FAIL = 'ONE_NEED_COEFFS_FAIL';
export const ONE_NEED_COEFFS_RESET = 'ONE_NEED_COEFFS_RESET';

export const CONTRIBUTION_LIST_REQUEST = 'CONTRIBUTION_LIST_REQUEST';
export const CONTRIBUTION_LIST_SUCCESS = 'CONTRIBUTION_LIST_SUCCESS';
export const CONTRIBUTION_LIST_FAIL = 'CONTRIBUTION_LIST_FAIL';
export const CONTRIBUTION_LIST_RESET = 'CONTRIBUTION_LIST_RESET';

export const MY_PAID_NEEDS_REQUEST = 'MY_PAID_NEEDS_REQUEST';
export const MY_PAID_NEEDS_SUCCESS = 'MY_PAID_NEEDS_SUCCESS';
export const MY_PAID_NEEDS_FAIL = 'MY_PAID_NEEDS_FAIL';
export const MY_PAID_NEEDS_RESET = 'MY_PAID_NEEDS_RESET';

export const USER_SIGNATURES_REQUEST = 'USER_SIGNATURES_REQUEST';
export const USER_SIGNATURES_SUCCESS = 'USER_SIGNATURES_SUCCESS';
export const USER_SIGNATURES_FAIL = 'USER_SIGNATURES_FAIL';

export const SIGNATURE_REQUEST = 'SIGNATURE_REQUEST';
export const SIGNATURE_SUCCESS = 'SIGNATURE_SUCCESS';
export const SIGNATURE_FAIL = 'SIGNATURE_FAIL';
export const SIGNATURE_RESET = 'SIGNATURE_RESET';

export const GET_MILESTONES_REQUEST = 'GET_MILESTONES_REQUEST';
export const GET_MILESTONES_SUCCESS = 'GET_MILESTONES_SUCCESS';
export const GET_MILESTONES_FAIL = 'GET_MILESTONES_FAIL';

export const CREATE_MILESTONE_REQUEST = 'CREATE_MILESTONE_REQUEST';
export const CREATE_MILESTONE_SUCCESS = 'CREATE_MILESTONE_SUCCESS';
export const CREATE_MILESTONE_FAIL = 'CREATE_MILESTONE_FAIL';

export const ECOSYSTEM_MINT_REQUEST = 'ECOSYSTEM_MINT_REQUEST';
export const ECOSYSTEM_MINT_SUCCESS = 'ECOSYSTEM_MINT_SUCCESS';
export const ECOSYSTEM_MINT_FAIL = 'ECOSYSTEM_MINT_FAIL';

export const FAMILY_DISTANCE_RATIO_REQUEST = 'FAMILY_DISTANCE_RATIO_REQUEST';
export const FAMILY_DISTANCE_RATIO_SUCCESS = 'FAMILY_DISTANCE_RATIO_SUCCESS';
export const FAMILY_DISTANCE_RATIO_FAIL = 'FAMILY_DISTANCE_RATIO_FAIL';

export const FAMILY_ECOSYSTEM_PAYS_REQUEST = 'FAMILY_ECOSYSTEM_PAYS_REQUEST';
export const FAMILY_ECOSYSTEM_PAYS_SUCCESS = 'FAMILY_ECOSYSTEM_PAYS_SUCCESS';
export const FAMILY_ECOSYSTEM_PAYS_FAIL = 'FAMILY_ECOSYSTEM_PAYS_FAIL';
